// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP622WCWUrEsgEsWTDojEc_tCFc13H--Y',
    appId: '1:1001090847975:web:0f5a05b08b980564ba3e42',
    messagingSenderId: '1001090847975',
    projectId: 'green-urban-connect',
    authDomain: 'green-urban-connect.firebaseapp.com',
    storageBucket: 'green-urban-connect.firebasestorage.app',
    measurementId: 'G-3CSZR7QQ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnBgQVqmM8jjRqSSniGZo61z9nczSq0w',
    appId: '1:1001090847975:android:90938d047790919bba3e42',
    messagingSenderId: '1001090847975',
    projectId: 'green-urban-connect',
    storageBucket: 'green-urban-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFKIDqg8lAAZTL3oSWORGwUyuQnLveFc',
    appId: '1:1001090847975:ios:378dd7370166789fba3e42',
    messagingSenderId: '1001090847975',
    projectId: 'green-urban-connect',
    storageBucket: 'green-urban-connect.firebasestorage.app',
    iosBundleId: 'com.example.greenUrbanConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFKIDqg8lAAZTL3oSWORGwUyuQnLveFc',
    appId: '1:1001090847975:ios:378dd7370166789fba3e42',
    messagingSenderId: '1001090847975',
    projectId: 'green-urban-connect',
    storageBucket: 'green-urban-connect.firebasestorage.app',
    iosBundleId: 'com.example.greenUrbanConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP622WCWUrEsgEsWTDojEc_tCFc13H--Y',
    appId: '1:1001090847975:web:882ad727fb99224dba3e42',
    messagingSenderId: '1001090847975',
    projectId: 'green-urban-connect',
    authDomain: 'green-urban-connect.firebaseapp.com',
    storageBucket: 'green-urban-connect.firebasestorage.app',
    measurementId: 'G-8VDGPMGYVC',
  );
}
