import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:green_urban_connect/app_widget.dart';
import 'package:green_urban_connect/core/services/service_locator.dart';
import 'firebase_options.dart'; // Ensure this is generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  setupServiceLocator(); // Initialize service locator for dependency injection
  runApp(const AppWidget());
}